// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egilbjnsrsokrkucfznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnaWxiam5zcnNva3JrdWNmem5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTQxMjEsImV4cCI6MjA2NTUzMDEyMX0.IxwjuKqiIi4nobrrXiJRd2GpdTmxXvp7yd45TgcKNqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);